[package]
name = "tracelens-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
brotli = "8"
encoding_rs = "0.8"
flate2 = "1"
libc = "0.2"
libbpf-rs = "0.27"
rusqlite = { version = "0.32", features = ["bundled"] }
serde.workspace = true
serde_json.workspace = true
tracelens-events = { path = "../crates/events" }
zstd = "0.13"
